export const defaultCountry = {
  callingCode: "+91",
  cca2: "IN",
  flag: "🇮🇳",
  name: {
    bg: "Индия",
    by: "Індыя",
    cn: "印度",
    cz: "Indie",
    de: "Indien",
    ee: "India",
    el: "Ινδία",
    en: "India",
    ar: "الهند",
    es: "India",
    fr: "Inde",
    he: "הוֹדוּ",
    it: "India",
    jp: "インド",
    nl: "India",
    pl: "Indie",
    pt: "Índia",
    ro: "India",
    ru: "Индия",
    ua: "Індія",
    zh: "印度",
    tr: "Hindistan",
  },
  phoneMasks: ["#### ### ###"],
};

export const defaultUserDetails = {
  address_type: "",
  city: "",
  country: defaultCountry,
  email: "",
  full_name: "",
  house_no: "",
  id: "",
  is_active: false,
  is_admin: false,
  is_email_verified: false,
  is_phone_number_verified: false,
  phone_number: "",
  profile_pic: "",
  role: "",
  shop_name: "",
  street_name: "",
};
